"""Tests for the OpenAI-compatible /audio/transcriptions backend."""

from __future__ import annotations

import io
import json
import wave
from unittest.mock import MagicMock

import numpy as np
import pytest

from justsayit.config import Config
from justsayit.transcribe_openai import (
    OpenAIWhisperTranscriber,
    _build_multipart,
    _encode_wav,
)


# ---------------------------------------------------------------------------
# WAV encoding
# ---------------------------------------------------------------------------


def test_encode_wav_round_trips_through_wave_module():
    """Generated bytes must be a parseable mono-16-bit WAV at the
    requested sample rate — that's what every Whisper-style server
    accepts."""
    rng = np.random.default_rng(0)
    samples = rng.uniform(-0.5, 0.5, size=8000).astype(np.float32)
    wav_bytes = _encode_wav(samples, 16000)
    with wave.open(io.BytesIO(wav_bytes), "rb") as r:
        assert r.getnchannels() == 1
        assert r.getsampwidth() == 2
        assert r.getframerate() == 16000
        assert r.getnframes() == 8000


def test_encode_wav_clips_extreme_values():
    """Float samples outside [-1, 1] must clip to int16 range, not wrap."""
    samples = np.array([1.5, -1.5, 0.0], dtype=np.float32)
    wav_bytes = _encode_wav(samples, 16000)
    with wave.open(io.BytesIO(wav_bytes), "rb") as r:
        pcm = np.frombuffer(r.readframes(3), dtype=np.int16)
    assert pcm[0] == 32767
    assert pcm[1] == -32768
    assert pcm[2] == 0


# ---------------------------------------------------------------------------
# Multipart payload
# ---------------------------------------------------------------------------


def test_build_multipart_includes_required_fields():
    body, content_type = _build_multipart(
        wav_bytes=b"\x00\x01RIFFfake",
        model="whisper-1",
        language="en",
    )
    assert content_type.startswith("multipart/form-data; boundary=")
    boundary = content_type.split("boundary=", 1)[1]
    assert boundary.encode() in body
    # File part with the right disposition
    assert b'name="file"; filename="audio.wav"' in body
    assert b"Content-Type: audio/wav" in body
    assert b"\x00\x01RIFFfake" in body
    # Form fields
    assert b'name="model"' in body
    assert b"whisper-1" in body
    assert b'name="response_format"' in body
    assert b"json" in body
    assert b'name="language"' in body
    assert b"en" in body
    # Closing boundary
    assert body.endswith(f"--{boundary}--\r\n".encode())


def test_build_multipart_omits_language_when_blank():
    body, _ = _build_multipart(
        wav_bytes=b"x",
        model="whisper-1",
        language="",
    )
    assert b'name="language"' not in body


# ---------------------------------------------------------------------------
# Transcriber end-to-end (mocked urlopen)
# ---------------------------------------------------------------------------


def _make_cfg(**overrides):
    cfg = Config()
    cfg.model.backend = "openai"
    cfg.model.openai_endpoint = "https://api.example.com/v1"
    cfg.model.openai_model = "whisper-1"
    cfg.model.openai_api_key = "sk-test"
    for k, v in overrides.items():
        setattr(cfg.model, k, v)
    return cfg


def _fake_urlopen_returning(payload: bytes):
    def fake(req, timeout=None):
        resp = MagicMock()
        resp.read.return_value = payload
        resp.__enter__ = lambda self: self
        resp.__exit__ = lambda self, *a: False
        fake.captured = {
            "url": req.full_url,
            "headers": dict(req.header_items()),
            "data": req.data,
            "timeout": timeout,
        }
        return resp
    return fake


def test_transcribe_posts_to_audio_transcriptions(monkeypatch):
    cfg = _make_cfg()
    t = OpenAIWhisperTranscriber(cfg)
    fake = _fake_urlopen_returning(json.dumps({"text": "  hello world "}).encode())
    import justsayit.transcribe_openai as mod
    monkeypatch.setattr(mod.urllib.request, "urlopen", fake)

    samples = np.zeros(1600, dtype=np.float32)
    out = t.transcribe(samples, 16000)
    assert out == "hello world"
    assert fake.captured["url"] == "https://api.example.com/v1/audio/transcriptions"
    assert fake.captured["headers"]["Authorization"] == "Bearer sk-test"
    assert fake.captured["headers"]["Content-type"].startswith("multipart/form-data")
    # The body must contain a real WAV (RIFF header)
    assert b"RIFF" in fake.captured["data"]
    assert fake.captured["timeout"] == pytest.approx(60.0)


def test_transcribe_includes_language_when_set(monkeypatch):
    cfg = _make_cfg(openai_language="de")
    t = OpenAIWhisperTranscriber(cfg)
    fake = _fake_urlopen_returning(json.dumps({"text": "hallo"}).encode())
    import justsayit.transcribe_openai as mod
    monkeypatch.setattr(mod.urllib.request, "urlopen", fake)

    t.transcribe(np.zeros(1600, dtype=np.float32), 16000)
    assert b'name="language"' in fake.captured["data"]
    assert b"\r\n\r\nde\r\n" in fake.captured["data"]


def test_transcribe_handles_text_response_format(monkeypatch):
    """Some servers return text/plain; JSON parse fails → fall back to
    decoded body."""
    cfg = _make_cfg()
    t = OpenAIWhisperTranscriber(cfg)
    fake = _fake_urlopen_returning(b"hello plain text\n")
    import justsayit.transcribe_openai as mod
    monkeypatch.setattr(mod.urllib.request, "urlopen", fake)

    out = t.transcribe(np.zeros(1600, dtype=np.float32), 16000)
    assert out == "hello plain text"


def test_transcribe_empty_samples_returns_empty():
    """Don't waste an API call (or quota) on an empty buffer."""
    cfg = _make_cfg()
    t = OpenAIWhisperTranscriber(cfg)
    out = t.transcribe(np.array([], dtype=np.float32), 16000)
    assert out == ""


def test_transcribe_raises_when_no_key(monkeypatch, tmp_path):
    import justsayit.config as cfg_mod
    monkeypatch.setattr(cfg_mod, "config_dir", lambda: tmp_path)
    cfg_mod._DOTENV_LOADED = False
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)

    cfg = _make_cfg(openai_api_key="")
    t = OpenAIWhisperTranscriber(cfg)
    with pytest.raises(RuntimeError, match="OPENAI_API_KEY"):
        t.transcribe(np.zeros(1600, dtype=np.float32), 16000)


def test_constructor_requires_endpoint():
    cfg = Config()
    cfg.model.backend = "openai"
    with pytest.raises(ValueError, match="openai_endpoint"):
        OpenAIWhisperTranscriber(cfg)


def test_make_transcriber_dispatches_to_openai(monkeypatch):
    """make_transcriber must wire backend = "openai" to our transcriber."""
    from justsayit.transcribe import make_transcriber
    cfg = _make_cfg()
    t = make_transcriber(cfg, model_paths=None)
    assert isinstance(t, OpenAIWhisperTranscriber)
