"""Configuration package for justsayit. Import from here, not from submodules."""
from ._schema import (
    AudioConfig,
    VadConfig,
    ShortcutConfig,
    PasteConfig,
    ModelConfig,
    OverlayConfig,
    SoundConfig,
    PostprocessConfig,
    LogConfig,
    Config,
    _coerce_section,
)
from ._io import (
    config_dir,
    cache_dir,
    models_dir,
    load_dotenv,
    resolve_secret,
    load_config,
    save_config,
    save_state,
    state_path,
    render_config_toml,
    default_config_toml,
    ensure_dirs,
    ensure_config_file,
    ensure_filters_file,
    ensure_after_llm_filters_file,
    ensure_commented_form_file,
    _COMMENTED_FORM_MARKER,
    _DOTENV_LOADED,
    _default_filter_chain,
)

__all__ = [
    # Schema
    "AudioConfig",
    "VadConfig",
    "ShortcutConfig",
    "PasteConfig",
    "ModelConfig",
    "OverlayConfig",
    "SoundConfig",
    "PostprocessConfig",
    "LogConfig",
    "Config",
    "_coerce_section",
    # I/O
    "config_dir",
    "cache_dir",
    "models_dir",
    "load_dotenv",
    "resolve_secret",
    "load_config",
    "save_config",
    "save_state",
    "state_path",
    "render_config_toml",
    "default_config_toml",
    "ensure_dirs",
    "ensure_config_file",
    "ensure_filters_file",
    "ensure_after_llm_filters_file",
    "ensure_commented_form_file",
    "_COMMENTED_FORM_MARKER",
    "_DOTENV_LOADED",
]
